### ISSUE TITLE
Allow importing a .markdown file (Mac)

### ISSUE THREAD

**Issue by Fogview** [inlinecoder/tempad-support#9]
Exporting a file (from Google Drive) can't be imported without changing the extension to .txt. The .markdown files should be allowed in addition to .txt files).

**Comment by kisileno** [comment]
Right now Tempad on macOS has a filename filter in the Import menu. There we are using `.txt` and commonly used `.md` file extensions fitler. The `.markdown` extension can be easily added.

**Comment by kisileno** [comment]
Implemented in 1.47
